version: '3.8'
services:
  backend:
    build:
      context: .backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/taxi_app 
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JWT_SECRET=secret_token
    volumes:
      - ./src:/app
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxi_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: